require('dotenv').config()
const express = require('express')
const cors = require('cors')
const crypto = require('crypto')
const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const { Pool } = require('pg')
const nodemailer = require('nodemailer')

const app = express()
const port = Number(process.env.PORT || 8787)
const jwtSecret = process.env.JWT_SECRET || 'change-this-secret'
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }) : null
if (pool && !process.env.VERCEL) setInterval(() => { pool.query('SELECT 1').catch(() => {}) }, 60000)
app.use(cors({ origin: true, credentials: true }))
app.use((req, res, next) => (req.body ? next() : express.json({ limit: '5mb' })(req, res, next)))

function requireDatabase(req, res, next) { if (!pool) return res.status(503).json({ error: 'DATABASE_URL is not configured on the server' }); next() }
function issueToken(user) { return jwt.sign({ id: user.id, orgId: user.org_id, role: user.role, email: user.email }, jwtSecret, { expiresIn: '12h' }) }
function auth(req, res, next) { try { const token = String(req.headers.authorization || '').replace('Bearer ', ''); req.user = jwt.verify(token, jwtSecret); next() } catch { res.status(401).json({ error: 'Authentication required' }) } }
function adminOnly(req, res, next) { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Administrator access required' }); next() }
function makeCode() { return String(crypto.randomInt(100000, 999999)) }
async function sendMail(to, subject, text) {
  if (!process.env.SMTP_HOST) return
  const transporter = nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_APP_PASSWORD } })
  await transporter.sendMail({ from: process.env.SMTP_FROM || process.env.SMTP_USER, to, subject, text })
}

app.get('/api/health', (req, res) => res.json({ ok: true, database: Boolean(pool) }))
app.post('/api/auth/admin/signup', requireDatabase, async (req, res) => {
  const { shopName, fullName, email, password } = req.body
  if (!shopName || !fullName || !email || !password || password.length < 6) return res.status(400).json({ error: 'Shop, name, email, and a password of at least 6 characters are required' })
  const client = await pool.connect()
  try {
    await client.query('BEGIN')
    const existing = await client.query('select id from users where lower(email) = lower($1)', [email.trim()])
    if (existing.rowCount) throw new Error('Email already exists')
    const org = await client.query('insert into organizations (name) values ($1) returning *', [shopName.trim()])
    const passwordHash = await bcrypt.hash(password, 12)
    const token = crypto.randomBytes(32).toString('hex')
    const user = await client.query('insert into users (org_id, role, full_name, email, password_hash, is_active, setup_status, email_verified, email_confirmation_token) values ($1, $2, $3, lower($4), $5, true, $6, false, $7) returning id, org_id, role, full_name, email, is_active, setup_status, created_at', [org.rows[0].id, 'admin', fullName.trim(), email.trim(), passwordHash, 'setup_complete', token])
    await client.query('COMMIT')
    const url = `${process.env.PUBLIC_API_URL || `http://localhost:${port}`}/api/auth/confirm-email?token=${token}`
    sendMail(email, 'Confirm your StockCount admin email', `Confirm your StockCount email by opening this link:\n\n${url}\n\nThis link can only be used once.`).catch(() => {})
    res.status(201).json({ requiresConfirmation: true, email: email.trim() })
  } catch (error) { await client.query('ROLLBACK'); res.status(400).json({ error: error.message }) } finally { client.release() }
})
app.get('/api/auth/confirm-email', async (req, res) => { if (!pool) return res.status(503).send('Database is not configured'); const result = await pool.query('update users set email_verified = true, email_confirmation_token = null where email_confirmation_token = $1 returning email', [req.query.token]); if (!result.rowCount) return res.status(400).send('This confirmation link is invalid or expired.'); res.send('Email confirmed. You can return to StockCount and sign in.') })
app.post('/api/auth/login', requireDatabase, async (req, res) => { const { email, password, role } = req.body; const result = await pool.query('select * from users where lower(email) = lower($1) and is_active = true', [email]); const user = result.rows[0]; if (!user || (role && user.role !== role) || !user.password_hash || !(await bcrypt.compare(password, user.password_hash))) return res.status(401).json({ error: 'Invalid credentials' }); if (!user.email_verified) return res.status(403).json({ error: 'Confirm your email before signing in' }); res.json({ token: issueToken(user), user: publicUser(user) }) })
app.post('/api/auth/invite/verify', requireDatabase, async (req, res) => { const { shopName, email, role, code } = req.body; const result = await pool.query('select u.* from users u join organizations o on o.id = u.org_id where lower(o.name) = lower($1) and lower(u.email) = lower($2) and u.role = $3 and u.invite_code = $4 and u.is_active = true', [shopName, email, role, code]); if (!result.rowCount) return res.status(400).json({ error: 'Invalid invitation details' }); res.json({ user: publicUser(result.rows[0]) }) })
app.post('/api/auth/invite/request', requireDatabase, async (req, res) => { const { shopName, email, role } = req.body; const result = await pool.query('select u.* from users u join organizations o on o.id = u.org_id where lower(o.name) = lower($1) and lower(u.email) = lower($2) and u.role = $3 and u.is_active = true and u.setup_status = $4', [shopName, email, role, 'invited']); if (!result.rowCount) return res.status(400).json({ error: 'No active invitation matches that shop, email, and role' }); const code = makeCode(); await pool.query('update users set invite_code=$1 where id=$2', [code, result.rows[0].id]); await sendMail(email, 'StockCount verification code', `Your StockCount verification code is: ${code}`); res.json({ code: process.env.NODE_ENV === 'production' ? undefined : code }) })
app.post('/api/auth/invite/complete', requireDatabase, async (req, res) => { const { userId, fullName, password } = req.body; if (!userId || !fullName || !password || password.length < 6) return res.status(400).json({ error: 'Name and a password of at least 6 characters are required' }); const passwordHash = await bcrypt.hash(password, 12); const result = await pool.query('update users set full_name=$1, password_hash=$2, setup_status=$3, email_verified=true, invite_code=null where id=$4 and is_active=true and setup_status=$5 returning id,org_id,role,full_name,email,phone,is_active,setup_status,created_at', [fullName.trim(), passwordHash, 'setup_complete', userId, 'invited']); if (!result.rowCount) return res.status(400).json({ error: 'Invitation setup is no longer available' }); res.json(publicUser(result.rows[0])) })
app.get('/api/admin/data', requireDatabase, auth, async (req, res) => { const id = req.user.orgId; const [org, users, locations, zones, items, sessions, logs, uploads] = await Promise.all([pool.query('select id,name,variance_threshold_pct,variance_threshold_units from organizations where id=$1', [id]), pool.query('select id,org_id,role,full_name,email,phone,is_active,setup_status,created_at from users where org_id=$1 order by created_at', [id]), pool.query('select * from locations where org_id=$1 order by name', [id]), pool.query('select z.* from zones z join locations l on l.id=z.location_id where l.org_id=$1 order by z.name', [id]), pool.query('select * from items where org_id=$1 order by name', [id]), pool.query('select * from count_sessions where org_id=$1 order by created_at desc', [id]), pool.query('select * from audit_logs where org_id=$1 order by created_at desc limit 20', [id]), pool.query('select id,org_id,file_name,columns,rows_preview,imported_count,zone_id,uploaded_by,created_at from excel_uploads where org_id=$1 order by created_at desc', [id])]); res.json({ source: 'neon', org: org.rows[0], users: users.rows, locations: locations.rows, zones: zones.rows, items: items.rows, sessions: sessions.rows, logs: logs.rows, uploads: uploads.rows }) })
app.patch('/api/admin/users/:id/status', requireDatabase, auth, adminOnly, async (req, res) => { const result = await pool.query('update users set is_active=$1 where id=$2 and org_id=$3 returning id,org_id,role,full_name,email,phone,is_active,setup_status,created_at', [Boolean(req.body.isActive), req.params.id, req.user.orgId]); res.json(result.rows[0]) })
app.patch('/api/admin/organizations/:id/thresholds', requireDatabase, auth, adminOnly, async (req, res) => { const result = await pool.query('update organizations set variance_threshold_pct=$1, variance_threshold_units=$2 where id=$3 and id=$4 returning id,name,variance_threshold_pct,variance_threshold_units', [req.body.pct, req.body.units, req.params.id, req.user.orgId]); res.json(result.rows[0]) })
app.post('/api/admin/users', requireDatabase, auth, adminOnly, async (req, res) => { const { full_name, email, role, phone } = req.body; if (!full_name || !email || !role) return res.status(400).json({ error: 'Name, email, and role are required' }); const existing = await pool.query('select id from users where org_id=$1 and lower(email)=lower($2)', [req.user.orgId, email]); if (existing.rowCount) return res.status(400).json({ error: 'That email is already a member of this shop' }); const code = makeCode(); const result = await pool.query('insert into users (org_id,full_name,email,role,phone,is_active,setup_status,invite_code,email_verified) values ($1,$2,lower($3),$4,$5,true,\'invited\',$6,true) returning id,org_id,role,full_name,email,phone,is_active,setup_status,created_at', [req.user.orgId, full_name.trim(), email.trim(), role, phone || null, code]); try { await sendMail(email, 'StockCount invitation', `Your StockCount invitation code is: ${code}`) } catch (error) { console.error('Invite email failed:', error.message) } res.status(201).json(result.rows[0]) })
app.post('/api/admin/locations', requireDatabase, auth, adminOnly, async (req, res) => { const { name, type, address } = req.body; if (!String(name || '').trim() || !['warehouse', 'store', 'site'].includes(type)) return res.status(400).json({ error: 'A location name and type (warehouse, store, or site) are required' }); const result = await pool.query('insert into locations (org_id,name,type,address) values ($1,$2,$3,$4) returning *', [req.user.orgId, String(name).trim(), type, String(address || '').trim() || null]); res.status(201).json(result.rows[0]) })
app.post('/api/admin/zones', requireDatabase, auth, adminOnly, async (req, res) => { const { location_id, name, code } = req.body; if (!location_id || !String(name || '').trim()) return res.status(400).json({ error: 'A location and zone name are required' }); const location = await pool.query('select id from locations where id=$1 and org_id=$2', [location_id, req.user.orgId]); if (!location.rowCount) return res.status(404).json({ error: 'Location not found' }); const result = await pool.query('insert into zones (location_id,name,code) values ($1,$2,$3) returning *', [location_id, String(name).trim(), String(code || '').trim() || null]); res.status(201).json(result.rows[0]) })
app.post('/api/admin/items', requireDatabase, auth, adminOnly, async (req, res) => { const rows = Array.isArray(req.body.items) ? req.body.items : [req.body]; const values = []; const placeholders = rows.map((item, i) => { const offset = i * 8; values.push(req.user.orgId, item.zone_id, item.name, item.sku, item.unit || 'unit', item.system_qty || 0, item.barcode || null, item.category || null); return `($${offset + 1},$${offset + 2},$${offset + 3},$${offset + 4},$${offset + 5},$${offset + 6},$${offset + 7},$${offset + 8})` }).join(','); const result = await pool.query(`insert into items (org_id,zone_id,name,sku,unit,system_qty,barcode,category) values ${placeholders} returning *`, values); res.status(201).json(result.rows) })
app.post('/api/admin/excel-uploads', requireDatabase, auth, adminOnly, async (req, res) => { const { fileName, columns, rowsPreview, importedCount, zoneId, rawData } = req.body; if (!fileName) return res.status(400).json({ error: 'File name is required' }); const result = await pool.query('insert into excel_uploads (org_id,file_name,columns,rows_preview,imported_count,zone_id,uploaded_by,raw_data) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id,org_id,file_name,columns,rows_preview,imported_count,zone_id,uploaded_by,created_at', [req.user.orgId, fileName, JSON.stringify(columns || []), JSON.stringify(rowsPreview || []), importedCount || 0, zoneId || null, req.user.id, JSON.stringify(rawData || [])]); res.status(201).json(result.rows[0]) })
app.post('/api/admin/sessions', requireDatabase, auth, adminOnly, async (req, res) => { const { name, location_id, zone_id, item_ids, counter_ids, mode, auditor_id } = req.body; if (!item_ids?.length || !counter_ids?.length || item_ids.length < counter_ids.length) return res.status(400).json({ error: 'Select at least one product per counter' }); const values = []; const placeholders = counter_ids.map((counterId, index) => { const assigned = item_ids.filter((_, itemIndex) => itemIndex % counter_ids.length === index); const offset = values.length; values.push(req.user.orgId, location_id, zone_id, counter_ids.length === 1 ? name : `${name} - Assignment ${index + 1}`, mode || 'blind', assigned, counterId, auditor_id || null); return `($${offset + 1},$${offset + 2},$${offset + 3},$${offset + 4},$${offset + 5},$${offset + 6},$${offset + 7},$${offset + 8})` }).join(','); const result = await pool.query(`insert into count_sessions (org_id,location_id,zone_id,name,mode,item_ids,assigned_counter_id,auditor_id) values ${placeholders} returning *`, values); res.status(201).json(result.rows) })
app.get('/api/mobile/org', requireDatabase, auth, async (req, res) => { const result = await pool.query('select id,name,variance_threshold_pct,variance_threshold_units,created_at from organizations where id=$1', [req.user.orgId]); res.json(result.rows[0]) })
app.get('/api/mobile/sessions', requireDatabase, auth, async (req, res) => { const params = [req.user.orgId]; let sql = 'select * from count_sessions where org_id=$1 and (assigned_counter_id=$2 or assigned_counter_2_id=$2 or auditor_id=$2)'; params.push(req.user.id); if (req.query.status) { params.push(req.query.status); sql += ` and status=$${params.length}` } const result = await pool.query(sql + ' order by created_at desc', params); res.json(result.rows) })
app.get('/api/mobile/sessions/:id', requireDatabase, auth, async (req, res) => { const result = await pool.query('select * from count_sessions where id=$1 and org_id=$2', [req.params.id, req.user.orgId]); res.json(result.rows[0] || null) })
app.get('/api/mobile/sessions/:id/items', requireDatabase, auth, async (req, res) => { const session = await pool.query('select * from count_sessions where id=$1 and org_id=$2 and (assigned_counter_id=$3 or assigned_counter_2_id=$3 or auditor_id=$3)', [req.params.id, req.user.orgId, req.user.id]); if (!session.rowCount) return res.status(404).json({ error: 'Session not found' }); const canSeeSystemQuantity = session.rows[0].mode === 'visible' || session.rows[0].auditor_id === req.user.id; const result = await pool.query(`select i.*, e.id as entry_id, e.counted_qty, e.system_qty as entry_system_qty, e.variance, e.counted_by, e.counted_at, e.is_flagged, e.notes, e.count_round, e.witnessed, e.witness_name from items i join count_sessions s on s.id=$1 and s.org_id=$2 and i.id = any(s.item_ids) left join lateral (select * from count_entries where session_id=s.id and item_id=i.id order by count_round desc, counted_at desc limit 1) e on true order by i.name`, [req.params.id, req.user.orgId]); res.json(result.rows.map(row => ({ system_qty: canSeeSystemQuantity ? row.system_qty : null, item: { id: row.id, org_id: row.org_id, zone_id: row.zone_id, name: row.name, barcode: row.barcode, sku: row.sku, unit: row.unit, category: row.category, system_qty: canSeeSystemQuantity ? row.system_qty : null, image_url: row.image_url, created_at: row.created_at, updated_at: row.updated_at }, entry: row.entry_id ? { id: row.entry_id, session_id: req.params.id, item_id: row.id, counted_qty: row.counted_qty, system_qty: canSeeSystemQuantity ? row.entry_system_qty : null, variance: row.variance, counted_by: row.counted_by, counted_at: row.counted_at, is_flagged: row.is_flagged, notes: row.notes, count_round: row.count_round, witnessed: row.witnessed, witness_name: row.witness_name } : null }))) })
app.get('/api/mobile/sessions/:id/entries', requireDatabase, auth, async (req, res) => { const result = await pool.query('select e.*, i.name as item_name, i.sku, i.barcode, u.full_name as counter_name from count_entries e join count_sessions s on s.id=e.session_id and s.org_id=$2 and (s.assigned_counter_id=$3 or s.assigned_counter_2_id=$3 or s.auditor_id=$3) join items i on i.id=e.item_id join users u on u.id=e.counted_by where e.session_id=$1 order by e.counted_at', [req.params.id, req.user.orgId, req.user.id]); res.json(result.rows.map(row => ({ ...row, item: { id: row.item_id, name: row.item_name, sku: row.sku, barcode: row.barcode }, counter: { id: row.counted_by, full_name: row.counter_name } }))) })
app.post('/api/mobile/sessions/:id/start', requireDatabase, auth, async (req, res) => { const result = await pool.query('update count_sessions set status=$1, updated_at=now() where id=$2 and org_id=$3 and assigned_counter_id=$4 and status=$5 returning *', ['in_progress', req.params.id, req.user.orgId, req.user.id, 'draft']); if (!result.rowCount) return res.status(400).json({ error: 'Session cannot be started' }); res.json(result.rows[0]) })
app.post('/api/mobile/sessions/:id/entries', requireDatabase, auth, async (req, res) => { const { itemId, countedQty, notes, witnessed, witnessName } = req.body; const session = await pool.query('select s.*, o.variance_threshold_pct, o.variance_threshold_units from count_sessions s join organizations o on o.id=s.org_id where s.id=$1 and s.org_id=$2 and (s.assigned_counter_id=$3 or s.assigned_counter_2_id=$3) and s.status in ($4,$5)', [req.params.id, req.user.orgId, req.user.id, 'in_progress', 'recount_assigned']); const item = await pool.query('select * from items where id=$1 and org_id=$2', [itemId, req.user.orgId]); if (!session.rowCount || !item.rowCount) return res.status(404).json({ error: 'Session or item not found' }); const current = await pool.query('select count(*)::int as count from count_entries where session_id=$1 and item_id=$2', [req.params.id, itemId]); const countRound = current.rows[0].count + 1; if (countRound === 3 && (!witnessed || !String(witnessName || '').trim())) return res.status(400).json({ error: 'A third-party witness name is required for the third count' }); const product = item.rows[0]; const variance = Number(countedQty) - Number(product.system_qty); const isFlagged = Math.abs(variance) > 0 && (Math.abs(variance / Number(product.system_qty || 1)) * 100 > Number(session.rows[0].variance_threshold_pct) || Math.abs(variance) > Number(session.rows[0].variance_threshold_units)); const result = await pool.query('insert into count_entries (session_id,item_id,counted_qty,system_qty,variance,counted_by,is_flagged,notes,count_round,witnessed,witness_name) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *', [req.params.id, itemId, countedQty, product.system_qty, variance, req.user.id, isFlagged, notes || null, countRound, Boolean(witnessed), witnessName?.trim() || null]); res.status(201).json(result.rows[0]) })
app.post('/api/mobile/sessions/:id/submit', requireDatabase, auth, async (req, res) => { const items = await pool.query('select i.id from items i join count_sessions s on s.id=$1 and s.org_id=$2 and s.assigned_counter_id=$3 and i.id=any(s.item_ids)', [req.params.id, req.user.orgId, req.user.id]); const entries = await pool.query('select distinct on (item_id) item_id, variance, count_round from count_entries where session_id=$1 order by item_id, count_round desc', [req.params.id]); const latest = new Map(entries.rows.map(row => [row.item_id, row])); if (!items.rowCount || items.rows.some(item => !latest.has(item.id))) return res.status(400).json({ error: 'Every item must be counted before submission' }); if (items.rows.some(item => latest.get(item.id).variance !== 0 && latest.get(item.id).count_round < 3)) return res.status(400).json({ error: 'Every item with a variance must be recounted before submission' }); const result = await pool.query('update count_sessions set status=$1, submitted_at=now(), updated_at=now() where id=$2 and org_id=$3 and assigned_counter_id=$4 and status in ($5,$6) returning *', ['submitted', req.params.id, req.user.orgId, req.user.id, 'in_progress', 'recount_assigned']); if (!result.rowCount) return res.status(400).json({ error: 'Session cannot be submitted' }); res.json(result.rows[0]) })
app.post('/api/mobile/sessions/:id/approve', requireDatabase, auth, async (req, res) => { const client = await pool.connect(); try { await client.query('BEGIN'); const result = await client.query('update count_sessions set status=$1, auditor_id=$2, approved_at=now(), updated_at=now() where id=$3 and org_id=$4 and auditor_id=$2 and status=$5 returning *', ['approved', req.user.id, req.params.id, req.user.orgId, 'submitted']); if (!result.rowCount) return res.status(400).json({ error: 'Session cannot be approved' }); await client.query('update items i set system_qty=e.counted_qty, updated_at=now() from (select distinct on (item_id) item_id, counted_qty from count_entries where session_id=$1 order by item_id, count_round desc) e where i.id=e.item_id and i.org_id=$2', [req.params.id, req.user.orgId]); await client.query('insert into audit_logs (org_id,entity_type,entity_id,action,actor_id,payload) values ($1,$2,$3,$4,$5,$6)', [req.user.orgId, 'session', req.params.id, 'approved', req.user.id, JSON.stringify({ entries_updated: true })]); await client.query('COMMIT'); res.json(result.rows[0]) } catch (error) { await client.query('ROLLBACK'); res.status(400).json({ error: error.message }) } finally { client.release() } })
app.post('/api/mobile/sessions/:id/reject', requireDatabase, auth, async (req, res) => { const result = await pool.query('update count_sessions set status=$1, auditor_id=$2, rejected_at=now(), reject_reason=$3, updated_at=now() where id=$4 and org_id=$5 and auditor_id=$2 and status=$6 returning *', ['rejected', req.user.id, req.body.reason || 'Rejected by auditor', req.params.id, req.user.orgId, 'submitted']); if (!result.rowCount) return res.status(400).json({ error: 'Session cannot be rejected' }); await pool.query('insert into audit_logs (org_id,entity_type,entity_id,action,actor_id,payload,reason) values ($1,$2,$3,$4,$5,$6,$7)', [req.user.orgId, 'session', req.params.id, 'rejected', req.user.id, '{}', req.body.reason || null]); res.json(result.rows[0]) })
app.post('/api/mobile/sessions/:id/recount', requireDatabase, auth, async (req, res) => { const result = await pool.query('update count_sessions set status=$1, assigned_counter_id=$2, auditor_id=$3, updated_at=now() where id=$4 and org_id=$5 and auditor_id=$3 and status in ($6,$7) returning *', ['recount_assigned', req.body.counterId, req.user.id, req.params.id, req.user.orgId, 'submitted', 'rejected']); if (!result.rowCount) return res.status(400).json({ error: 'Session cannot be assigned for recount' }); await pool.query('insert into audit_logs (org_id,entity_type,entity_id,action,actor_id,payload) values ($1,$2,$3,$4,$5,$6)', [req.user.orgId, 'session', req.params.id, 'recount_assigned', req.user.id, JSON.stringify({ counter: req.body.counterId })]); res.json(result.rows[0]) })
app.get('/api/mobile/locations', requireDatabase, auth, async (req, res) => { const result = await pool.query('select * from locations where org_id=$1 order by name', [req.user.orgId]); res.json(result.rows) })
app.get('/api/mobile/zones', requireDatabase, auth, async (req, res) => { const result = await pool.query('select z.* from zones z join locations l on l.id=z.location_id where l.org_id=$1 and z.location_id=$2 order by z.name', [req.user.orgId, req.query.locationId]); res.json(result.rows) })
app.get('/api/mobile/items', requireDatabase, auth, async (req, res) => { const values = [req.user.orgId]; let sql = 'select * from items where org_id=$1'; if (req.query.zoneId) { values.push(req.query.zoneId); sql += ` and zone_id=$${values.length}` } if (req.query.search) { values.push(`%${req.query.search}%`); sql += ` and (name ilike $${values.length} or sku ilike $${values.length} or barcode ilike $${values.length})` } const result = await pool.query(sql + ' order by name', values); res.json(result.rows) })
app.get('/api/mobile/items/barcode/:barcode', requireDatabase, auth, async (req, res) => { const result = await pool.query('select * from items where org_id=$1 and barcode=$2', [req.user.orgId, req.params.barcode]); res.json(result.rows[0] || null) })
app.get('/api/mobile/audit-logs', requireDatabase, auth, async (req, res) => { const result = await pool.query('select * from audit_logs where org_id=$1 order by created_at desc limit 100', [req.user.orgId]); res.json(result.rows) })
app.post('/api/mobile/audit-logs', requireDatabase, auth, async (req, res) => { const { entityType, entityId, note } = req.body; const result = await pool.query('insert into audit_logs (org_id,entity_type,entity_id,action,actor_id,payload) values ($1,$2,$3,$4,$5,$6) returning *', [req.user.orgId, entityType, entityId, 'note', req.user.id, JSON.stringify({ note })]); res.status(201).json(result.rows[0]) })

module.exports = app
function publicUser(user) { return { id: user.id, org_id: user.org_id, role: user.role, full_name: user.full_name, email: user.email, phone: user.phone, is_active: user.is_active, setup_status: user.setup_status, created_at: user.created_at } }
